server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #false表示不向服务中心注册自己
    fetch-registry: true #false 表示自己就是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #向eureka查询和注册服务都通过这个地址
  instance:
    instance-id: order80
    prefer-ip-address: true #显示ip信息