server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #false表示不向服务中心注册自己
    fetch-registry: true #false 表示自己就是注册中心
    service-url:
      defaultZone: http://localhost:7001/eureka/ #向eureka查询和注册服务都通过这个地址
